spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ttms?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

server:
  port: 8080

logging:
  level:
    root: info
    com.xupt: debug
  file:
    name: log/blog-dev.log
